Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.box = "u16"
            node.vm.hostname="node#{i}"
            node.vm.network "private_network", ip: "192.168.59.1#{i}"

            node.vm.provider "virtualbox" do |v|
                v.name = "node#{i}"
                v.memory = 1024
                v.cpus = 1
            end

            config.vm.provision "shell" do |s|
                s.path = "script.sh"
                s.args = ["#{i}", "192.168.59.1#{i}"]
            end
        end
    end
end
